---
- name: Check Connectivity with Windows Hosts
  hosts: all  # Targets all hosts in your inventory
  gather_facts: no  # Skips gathering system facts to speed up the process

  tasks:
    - name: Ping Windows Hosts
      ansible.windows.win_ping:  # Uses the win_ping module for Windows hosts
