---
- name: Collect Hostnames
  hosts: all
  gather_facts: no
  tasks:
    - name: Initialize host counter
      set_fact:
        host_counter: 0

    - name: Increment host counter
      set_fact:
        host_counter: "{{ host_counter | int + 1 }}"
      delegate_to: localhost
      run_once: true

    - name: Get hostname using PowerShell
      ansible.windows.win_shell: |
        [System.Net.Dns]::GetHostName()
      register: hostname_result

    - name: Set formatted hostname
      set_fact:
        formatted_hostname: "{{ host_counter }}:{{ ansible_host }}:{{ hostname_result.stdout | trim }}"

    - name: Display formatted hostname
      debug:
        msg: "{{ formatted_hostname }}"
