---
- name: Collect Hostnames
  hosts: all
  gather_facts: no
  tasks:
    - name: Get hostname using PowerShell
      ansible.windows.win_shell: |
        [System.Net.Dns]::GetHostName()
      register: hostname_result

    - name: Set formatted hostname
      set_fact:
        formatted_hostname: "{{ ansible_host }}:{{ hostname_result.stdout | trim }}"

    - name: Display formatted hostname
      debug:
        msg: "{{ formatted_hostname }}"
