---
- name: Disable Windows Updates
  hosts: windows
  tasks:
    - name: Stop Windows Update service
      win_service:
        name: wuauserv
        start_mode: disabled
        state: stopped

    - name: Disable Windows Update using Registry
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
        value: 1
        type: dword

    - name: Verify Windows Update service is stopped and disabled
      win_service_info:
        name: wuauserv
      register: win_update_service_status

    - name: Display Windows Update service status
      debug:
        msg: "Windows Update service status: {{ win_update_service_status }}"
        
    - name: Verify NoAutoUpdate registry key
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: NoAutoUpdate
      register: verify_no_auto_update

    - name: Display NoAutoUpdate registry key status
      debug:
        msg: "NoAutoUpdate registry key status: {{ verify_no_auto_update }}"
