---
- name: Setup Nudge on Mac
  hosts: all
  become: yes
  tasks:

    - name: Execute Nudgehelper.sh with bash
      command: "bash /tmp/Nudgehelper.sh"
      tags:
        - execute

    - name: Execute Nudge_Latest.sh with bash
      command: "bash /tmp/Nudge_Latest.sh"
      tags:
        - execute



