---
- name: Setup Nudge on Mac
  hosts: all
  become: yes
  tasks:
    - name: Download Nudge_Latest.sh
      get_url:
        url: "https://github.com/qowefj/ansible_concircle/blob/main/Nudge_Latest.sh"
        dest: "/tmp/Nudge_Latest.sh"
      tags:
        - download

    - name: Download com.github.macadmins.Nudge.json
      get_url:
        url: "https://github.com/qowefj/ansible_concircle/blob/main/com.github.macadmins.Nudge.json"
        dest: "/tmp/com.github.macadmins.Nudge.json"
      tags:
        - download

    - name: Make Nudge_Latest.sh executable
      file:
        path: "/tmp/Nudge_Latest.sh"
        mode: "0755"
      tags:
        - permissions

    - name: Execute Nudge_Latest.sh
      command: "/tmp/Nudge_Latest.sh"
      tags:
        - execute

    - name: Move com.github.macadmins.Nudge.json to /Library/Preferences
      command: "mv /tmp/com.github.macadmins.Nudge.json /Library/Preferences/com.github.macadmins.Nudge.json"
      tags:
        - move

    - name: Start Nudge.app
      command: "open /Applications/Utilities/Nudge.app"
      tags:
        - start
