---
- name: Deploy Nudge and configure for macOS updates
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Download the Nudge JSON configuration file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.json
        dest: /Library/Preferences/com.github.macadmins.Nudge.json
        mode: '0644'
        owner: root
        group: wheel
      become: yes
      become_method: sudo
      become_user: root

    - name: Download the Nudge LaunchAgent plist file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.plist
        dest: /Library/LaunchAgents/com.github.macadmins.Nudge.plist
        mode: '0644'
        owner: root
        group: wheel
      become: yes
      become_method: sudo
      become_user: root

    - name: Download the Nudge pkg installer
      ansible.builtin.get_url:
        url: https://github.com/qowefj/ansible_concircle/raw/main/nudge/Nudge-2.0.3.81727.pkg
        dest: /tmp/Nudge-2.0.3.81727.pkg
      become: yes
      become_method: sudo
      become_user: root

    - name: Install the Nudge pkg
      ansible.builtin.command:
        cmd: installer -pkg /tmp/Nudge-2.0.3.81727.pkg -target /
      become: yes
      become_method: sudo
      become_user: root

    - name: Load the Nudge LaunchAgent
      community.general.launchd:
        name: com.github.macadmins.Nudge
        state: loaded
        enabled: yes
      become: yes
      become_method: sudo
      become_user: root
