---
- name: Deploy Nudge and configure for macOS updates
  hosts: all
  become: yes

  tasks:
    - name: Ensure /Library/Preferences directory exists
      file:
        path: /Library/Preferences
        state: directory
        owner: root
        group: wheel
        mode: '0755'

    - name: Download the Nudge JSON configuration file
      get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.json
        dest: /Library/Preferences/com.github.macadmins.Nudge.json
        mode: '0644'
        owner: root
        group: wheel

    - name: Ensure /Library/LaunchAgents directory exists
      file:
        path: /Library/LaunchAgents
        state: directory
        owner: root
        group: wheel
        mode: '0755'

    - name: Download the Nudge LaunchAgent plist file
      get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.plist
        dest: /Library/LaunchAgents/com.github.macadmins.Nudge.plist
        mode: '0644'
        owner: root
        group: wheel

    - name: Download the Nudge pkg installer
      get_url:
        url: https://github.com/qowefj/ansible_concircle/raw/main/nudge/Nudge-2.0.3.81727.pkg
        dest: /tmp/Nudge-2.0.3.81727.pkg

    - name: Install the Nudge pkg
      shell: installer -pkg /tmp/Nudge-2.0.3.81727.pkg -target /
      args:
        creates: /Applications/Utilities/Nudge.app

    - name: Load the Nudge LaunchAgent
      shell: launchctl load /Library/LaunchAgents/com.github.macadmins.Nudge.plist
      args:
        creates: /Library/LaunchAgents/com.github.macadmins.Nudge.plist

    - name: Start the Nudge application
      shell: /Applications/Utilities/Nudge.app/Contents/MacOS/Nudge
