---
- name: Deploy Nudge and configure for macOS updates
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install required collection
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.general

    - name: Download the Nudge JSON configuration file to /tmp
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.json
        dest: /tmp/com.github.macadmins.Nudge.json
        mode: '0644'
        owner: root
        group: wheel

    - name: Move Nudge JSON configuration file to /Library/Preferences
      ansible.builtin.command:
        cmd: mv /tmp/com.github.macadmins.Nudge.json /Library/Preferences/com.github.macadmins.Nudge.json
      become: yes
      become_method: sudo

    - name: Download the Nudge LaunchAgent plist file to /tmp
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.plist
        dest: /tmp/com.github.macadmins.Nudge.plist
        mode: '0644'
        owner: root
        group: wheel

    - name: Move Nudge LaunchAgent plist file to /Library/LaunchAgents
      ansible.builtin.command:
        cmd: mv /tmp/com.github.macadmins.Nudge.plist /Library/LaunchAgents/com.github.macadmins.Nudge.plist
      become: yes
      become_method: sudo

    - name: Download the Nudge pkg installer to /tmp
      ansible.builtin.get_url:
        url: https://github.com/qowefj/ansible_concircle/raw/main/nudge/Nudge-2.0.3.81727.pkg
        dest: /tmp/Nudge-2.0.3.81727.pkg

    - name: Install the Nudge pkg
      ansible.builtin.command:
        cmd: installer -pkg /tmp/Nudge-2.0.3.81727.pkg -target /
      become: yes
      become_method: sudo

    - name: Load the Nudge LaunchAgent
      community.general.launchd:
        name: com.github.macadmins.Nudge
        state: loaded
        enabled: yes
