---
- name: Deploy Nudge and configure for macOS updates
  hosts: all
  become: yes

  tasks:
    - name: Download the Nudge JSON configuration file
      get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.json
        dest: /Library/Preferences/com.github.macadmins.Nudge.json
        mode: '0644'
        owner: root
        group: wheel

    - name: Download the Nudge LaunchAgent plist file
      get_url:
        url: https://raw.githubusercontent.com/qowefj/ansible_concircle/main/nudge/com.github.macadmins.Nudge.plist
        dest: /Library/LaunchAgents/com.github.macadmins.Nudge.plist
        mode: '0644'
        owner: root
        group: wheel

    - name: Download the Nudge pkg installer
      get_url:
        url: https://github.com/qowefj/ansible_concircle/raw/main/nudge/Nudge-2.0.3.81727.pkg
        dest: /tmp/Nudge-2.0.3.81727.pkg

    - name: Install the Nudge pkg
      command: installer -pkg /tmp/Nudge-2.0.3.81727.pkg -target /

    - name: Load the Nudge LaunchAgent
      launchd:
        name: com.github.macadmins.Nudge
        state: loaded
        enabled: yes
