---
- name: Change Wallpaper for All Users on Windows 10
  hosts: all
  vars:
    wallpaper_url: "https://raw.githubusercontent.com/qowefj/ansible_concircle/main/wallpaper.jpeg"
    local_wallpaper_path: "C:\\Windows\\Web\\Wallpaper\\Wallpaper.jpeg"
    ps_script_url: "https://raw.githubusercontent.com/qowefj/ansible_concircle/main/SetWallpaper.ps1"
    local_ps_script_path: "C:\\Windows\\Web\\Wallpaper\\SetWallpaper.ps1"
  tasks:
    - name: Download wallpaper image
      win_get_url:
        url: "{{ wallpaper_url }}"
        dest: "{{ local_wallpaper_path }}"
        force: yes

    - name: Download PS Script
      win_get_url:
        url: "{{ ps_script_url }}"
        dest: "{{ local_ps_script_path }}"
        force: yes

    - name: Add logon script for all users
      win_regedit:
        path: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
        name: SetWallpaper
        data: 'powershell.exe -ExecutionPolicy Bypass -File C:\Windows\Web\Wallpaper\SetWallpaper.ps1'
        type: string
