---
- name: Configure Windows 10 Automatic Updates
  hosts: windows
  tasks:
    - name: Set Windows Update Service to auto start
      win_service:
        name: wuauserv
        start_mode: auto

    - name: Configure Automatic Updates to install every Saturday at 3 PM
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
        value: 6
        type: dword
      register: scheduled_install_day

    - name: Set scheduled install time to 3 PM
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
        value: 15
        type: dword
      when: scheduled_install_day is success
