---
- name: Configure Windows 10 Automatic Updates
  hosts: windows
  tasks:
    - name: Set Windows Update Service to auto start
      win_service:
        name: wuauserv
        start_mode: auto

    - name: Remove existing ScheduledInstallDay if present
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
        state: absent

    - name: Configure ScheduledInstallDay to Thursday
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
        value: 5
        type: dword

    - name: Verify ScheduledInstallDay was set
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
      register: verify_scheduled_install_day

    - name: Remove existing ScheduledInstallTime if present
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
        state: absent

    - name: Set scheduled install time to 1 PM
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
        value: 13
        type: dword

    - name: Verify ScheduledInstallTime was set
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
      register: verify_scheduled_install_time

    - name: Remove existing AlwaysAutoRebootAtScheduledTime if present
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AlwaysAutoRebootAtScheduledTime
        state: absent

    - name: Ensure automatic restart is enabled after updates
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AlwaysAutoRebootAtScheduledTime
        value: 1
        type: dword

    - name: Verify AlwaysAutoRebootAtScheduledTime was set
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AlwaysAutoRebootAtScheduledTime
      register: verify_auto_reboot

    - name: Remove existing RebootWarningTimeout if present
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: RebootWarningTimeout
        state: absent

    - name: Set auto reboot warning to 15 minutes
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: RebootWarningTimeout
        value: 15
        type: dword

    - name: Verify RebootWarningTimeout was set
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: RebootWarningTimeout
      register: verify_reboot_warning_timeout

    - name: Display verification results
      debug:
        msg:
          - "ScheduledInstallDay: {{ verify_scheduled_install_day }}"
          - "ScheduledInstallTime: {{ verify_scheduled_install_time }}"
          - "AlwaysAutoRebootAtScheduledTime: {{ verify_auto_reboot }}"
          - "RebootWarningTimeout: {{ verify_reboot_warning_timeout }}"
