---
- name: Configure Windows Update schedule and initiate updates
  hosts: windows
  gather_facts: no
  tasks:
    - name: Set the preferred update time to Saturday 1 PM (CET)
      win_shell: |
        $ScheduledInstallDay = 6  # Saturday
        $ScheduledInstallTime = 13  # 1 PM CET
        $serviceManager = New-Object -ComObject "Microsoft.Update.ServiceManager"
        $serviceManager.ClientApplicationID = "My App"
        $autoUpdate = New-Object -ComObject "Microsoft.Update.AutoUpdate"
        $settings = $autoUpdate.Settings
        $settings.ScheduledInstallDay = $ScheduledInstallDay
        $settings.ScheduledInstallTime = $ScheduledInstallTime
        $settings.NotificationLevel = 1
        $settings.Save()
      args:
        executable: powershell

    - name: Start downloading and installing updates
      win_shell: |
        Install-WindowsUpdate -AcceptAll -AutoReboot
      args:
        executable: powershell
