---
- name: Manage Windows 10 Updates
  hosts: windows
  tasks:
    - name: Install all critical and security updates and reboot if necessary
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        reboot: true
        log_path: C:\ansible_wu.txt

    - name: Verify ScheduledInstallDay
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallDay
      register: verify_scheduled_install_day

    - name: Verify ScheduledInstallTime
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: ScheduledInstallTime
      register: verify_scheduled_install_time

    - name: Verify AlwaysAutoRebootAtScheduledTime
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: AlwaysAutoRebootAtScheduledTime
      register: verify_auto_reboot

    - name: Verify RebootWarningTimeout
      win_reg_stat:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: RebootWarningTimeout
      register: verify_reboot_warning_timeout

    - name: Display verification results
      debug:
        msg:
          - "ScheduledInstallDay: {{ verify_scheduled_install_day }}"
          - "ScheduledInstallTime: {{ verify_scheduled_install_time }}"
          - "AlwaysAutoRebootAtScheduledTime: {{ verify_auto_reboot }}"
          - "RebootWarningTimeout: {{ verify_reboot_warning_timeout }}"
