---
- name: Ensure consistent hostnames on Windows hosts
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get current hostname
      win_shell: |
        (Get-WmiObject Win32_ComputerSystem).Name
      register: current_hostname

    - name: Analyze current hostname and determine new hostname
      set_fact:
        new_hostname: |
          {% set host_mapping = {
              'RD-CONGSTFLO-Concircle': 'CONGSTFLO',
              'RD-CONAIGWOL-concircle': 'CONAIGWOL',
              'RD-CONPESAND': 'CONPESAND',
              'RD-CONORIRON': 'CONORIRON',
              'RD-CONSTAMIL-concircle': 'CONSTAMIL',
              'RD-CONSTEDAV': 'CONSTEDAV',
              'RD-CONMEZGAB-concircle': 'CONMEZGAB',
              'RD-CONBELMAR': 'CONBELMAR',
              'RD-CONKOBDOM': 'CONKOBDOM'
          } %}
          {{ host_mapping.get(current_hostname.stdout.strip(), 'UNKNOWN') }}

    - name: Check if the hostname needs to be changed
      debug:
        msg: "Current hostname is {{ current_hostname.stdout }}. New hostname will be {{ new_hostname }}."
      when: new_hostname != 'UNKNOWN'

    - name: Change hostname
      win_hostname:
        name: "{{ new_hostname }}"
      when: new_hostname != 'UNKNOWN' and new_hostname != current_hostname.stdout.strip()

    - name: Ensure the new hostname is valid before proceeding
      fail:
        msg: "The hostname could not be determined from the current hostname {{ current_hostname.stdout }}."
      when: new_hostname == 'UNKNOWN'
