---
- name: Install .msi file on Windows host
  hosts: windows
  tasks:
    - name: Ensure the C:\temp directory exists
      win_file:
        path: C:\temp
        state: directory

    - name: Download the .msi file with SSL verification disabled
      win_get_url:
        url: https://cpm.rp.concircle.com/fleet-osquery.msi
        dest: C:\temp\fleet-osquery.msi
        validate_certs: no

    - name: Install the .msi file
      win_package:
        path: C:\temp\fleet-osquery.msi
        state: present
