---
- name: Install .msi file on Windows host
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check if Fleet osquery is already installed
      win_shell: |
        Get-WmiObject -Class Win32_Product -Filter "Name = 'Fleet osquery'"
      register: fleet_osquery_installed
      failed_when: fleet_osquery_installed.stderr != ''

    - name: Ensure the C:\temp directory exists
      win_file:
        path: C:\temp
        state: directory
      when: fleet_osquery_installed.stdout == ''

    - name: Check if the .msi file already exists
      win_stat:
        path: C:\temp\fleet-osquery.msi
      register: msi_file
      when: fleet_osquery_installed.stdout == ''

    - name: Download the .msi file with SSL verification disabled
      win_get_url:
        url: https://cpm.rp.concircle.com/fleet-osquery.msi
        dest: C:\temp\fleet-osquery.msi
        validate_certs: no
      when: fleet_osquery_installed.stdout == '' and not msi_file.stat.exists

    - name: Install the .msi file
      win_package:
        path: C:\temp\fleet-osquery.msi
        state: present
      when: fleet_osquery_installed.stdout == ''
